/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    `maven-publish`
    signing
    kotlin("jvm")
}

group = "org.openbase"
description = "PlanetSudo is a reactive multi agent simulation game. This package can be used to prototype the artificial intelligence for a new team."


repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencies {
    implementation(libs.org.openbase.planetsudo.engine)
    implementation(kotlin("stdlib-jdk8"))
    testImplementation(libs.junit.junit)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(17)
}
